name: Deploy Web App (Dev)

on:
  pull_request:
    branches:
      - develop

jobs:
  deploy:
    environment: AWS Keys
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    permissions:
      deployments: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install Dependencies
        run: npm --force ci

      - name: Build React App
        env:
          REACT_APP_API_URL: ${{ secrets.API_URL }}
        run:
          PUBLIC_URL=/pr-${{github.event.pull_request.number}}/ NODE_ENV=development
          npm run build

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_FRONTEND_DEPLOYER_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_FRONTEND_DEPLOYER_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2 # Seoul

      - name: Deploy to S3
        env:
          aws-access-key-id: ${{ secrets.AWS_FRONTEND_DEPLOYER_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_FRONTEND_DEPLOYER_SECRET_ACCESS_KEY }}
        run: aws s3 sync --region ap-northeast-2 build s3://${{ vars.AWS_S3_DEV_PR_BUCKET_NAME }}/pr-${{ github.event.pull_request.number }}/ --delete

      - name: Invalidate CloudFront Cache
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_CLOUDFRONT_DEV_PR_DISRIBUTION_ID }} --paths "/pr-${{ github.event.pull_request.number }}/*"

      - name: Add Deployment URL to Actions Summary
        run: |
          echo "::notice::🚀 Deployment Successful! Preview URL: ${{vars.AWS_CLOUDFRONT_DEV_PR_URL}}/pr-${{ github.event.pull_request.number }}/"
