name: Deploy Development Web App to CloudFront & S3

on:
  pull_request:
    branches:
      - develop

jobs:
  deploy:
    environment: AWS Keys
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    outputs:
      preview-url: ${{ vars.AWS_CLOUDFRONT_STORYBOOK_URL }}/pr-${{ github.event.pull_request.number }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install Dependencies
        run: npm --force ci

      - name: Build React App
        run: npm run build-storybook

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_FRONTEND_DEPLOYER_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_FRONTEND_DEPLOYER_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2 # Seoul

      - name: Deploy to S3
        env:
          aws-access-key-id: ${{ secrets.AWS_FRONTEND_DEPLOYER_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_FRONTEND_DEPLOYER_SECRET_ACCESS_KEY }}
        run: PR_NUMBER=${{ github.event.pull_request.number }}
          aws s3 sync --region ap-northeast-2 storybook-static s3://${{ vars.AWS_S3_STORYBOOK_BUCKET_NAME }}/pr-${PR_NUMBER}/ --delete

      - name: Invalidate CloudFront Cache
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_CLOUDFRONT_STORYBOOK_DISRIBUTION_ID }} --paths "/pr-${{ github.event.pull_request.number }}/*"
