name: Deploy Web App (Prod)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    environment: AWS Keys
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install Dependencies
        run: npm --force ci

      - name: Setup .env
        run: |
          echo "REACT_APP_API_URL=${{ vars.API_URL_PROD }}" >> .env
          echo "REACT_APP_COGNITO_CLIENT_ID=${{ secrets.AWS_COGNITO_CLIENT_ID }}" >> .env
          echo "REACT_APP_COGNITO_REGION=${{ vars.AWS_REGION }}" >> .env
          echo "REACT_APP_DATAIKU_CHATBOT_URL=${{ vars.DATAIKU_CHATBOT_URL }}" >> .env
          echo "REACT_APP_DATAIKU_DASHBOARD_URL=${{ vars.DATAIKU_DASHBOARD_URL }}" >> .env
          echo "NODE_ENV=production" >> .env

      - name: Build React App
        run: npm run build

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_FRONTEND_DEPLOYER_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_FRONTEND_DEPLOYER_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2 # Seoul

      - name: Deploy to S3
        env:
          aws-access-key-id: ${{ secrets.AWS_FRONTEND_DEPLOYER_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_FRONTEND_DEPLOYER_SECRET_ACCESS_KEY }}
        run: aws s3 sync --region ${{vars.AWS_REGION}} build s3://${{ vars.AWS_S3_PROD_BUCKET_NAME }}/ --delete

      - name: Invalidate CloudFront Cache
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_CLOUDFRONT_PROD_DISRIBUTION_ID }} --paths "/*"

      - name: Add Deployment URL to Actions Summary
        run: |
          echo "::notice::🚀 Deployment Successful! Preview URL: https://bongsco.site"
